#!/bin/bash
#java 11 switch
rm -rf /etc/alternatives/javac
rm -rf /etc/alternatives/java
ln -s /usr/lib/jvm/java-11/bin/java  /etc/alternatives/java
ln -s /usr/lib/jvm/java-11/bin/javac  /etc/alternatives/javac
java -version
javac -version
